version: '3.8'

services:
  app:
    container_name: karasu-lab-api
    image: hashibutogarasu/karasu-lab-api:5.4.5 # x-release-please-version
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    env_file:
      - .env.production
    volumes:
      - ./configs:/app/configs
    restart: always
